### ISSUE TITLE
Play a sound everytime a Pomodoro interval ends

### ISSUE THREAD

**Issue by angelofallars** [angelofallars/pomoff#1]
Currently, the Pomodoro timer program just displays a pop-up every time a work or break interval ends. It should play a sound from the `sound/` folder as well to improve the user experience. It should be implemented for Linux-based systems.

**Comment by shivamchourasia4** [comment]
Hey there @angelofallars , I can try working on this.
You can assign this to me.

**Comment by angelofallars** [comment]
Sure thing, @shivamchourasia4! Make a fork and commit your changes there. You can make the program in `main.py` import another library, I'll handle the `requirements.txt` myself.

**Comment by shivamchourasia4** [comment]
Can you add "hacktoberfest-accepted" label on my PR as it is showing that this project is not participating in hacktoberfest.
Or you can also add "hacktoberfest" to the project as adding that label in issue is not working!
