### ISSUE TITLE
Run script [main.py] with argument

### ISSUE THREAD

**Issue by rivo2302** [angelofallars/pomoff#3]
@angelofallars 
 I suggest that we can run the main.py script **with arguments**.
As you can see here :   _https://github.com/rivo2302/pomoff/commit/307dac3cf54d16592757e215e2cad6e66f304f9b_

**Comment by angelofallars** [comment]
Very nice! Make a pull request on the `dev` branch and we'll work on integrating it in Pomoff.

**Comment by rivo2302** [comment]
@angelofallars ,  It's done !
